import os
import re
import datetime
import logging
from pathlib import Path
from .claude_runner import ClaudeRunner

logger = logging.getLogger(__name__)

class ShipflowOrchestrator:
    def __init__(self, target_dir: str, shipflow_repo_path: str):
        """
        :param target_dir: The project directory where shipflow artifacts will be written.
        :param shipflow_repo_path: Path to the shipflow source code (to read agents/skills).
        """
        self.target_dir = Path(target_dir).resolve()
        self.shipflow_repo_path = Path(shipflow_repo_path).resolve()

        # We assume the user wants the CLI to run in the target_dir
        self.runner = ClaudeRunner(cwd=str(self.target_dir))

        # Ensure docs/shipflow structure exists
        self.docs_dir = self.target_dir / "docs" / "shipflow"

    def _slugify(self, text: str) -> str:
        slug = text.lower()
        slug = re.sub(r'[^a-z0-9]+', '-', slug)
        slug = slug.strip('-')
        # cap length at 40
        if len(slug) > 40:
            slug = slug[:40]
            # Try to cut on word boundary
            last_dash = slug.rfind('-')
            if last_dash > 0:
                slug = slug[:last_dash]
        return slug

    def _get_agent_path(self, agent_name: str) -> str:
        return str(self.shipflow_repo_path / "agents" / f"{agent_name}.md")

    def sf_init(self):
        """
        Initialize the shipflow structure in the target directory.
        """
        logger.info("Initializing ShipFlow directories...")
        dirs_to_create = [
            "briefs", "stories", "decisions", "releases", "retros",
            "diaries", "discovery", "sessions", "archive"
        ]
        for d in dirs_to_create:
            (self.docs_dir / d).mkdir(parents=True, exist_ok=True)

        index_file = self.docs_dir / "index.md"
        if not index_file.exists():
            index_file.write_text("<!-- Auto-regenerated -->\n# ShipFlow Index\n", encoding="utf-8")

        logger.info("Initialization complete.")

    def sf_discover(self, idea: str) -> str:
        """
        Kick off a Discover-phase dialogue for a new idea.
        """
        logger.info(f"Running /sf-discover for idea: {idea}")
        base_slug = self._slugify(idea)

        discovery_base = self.docs_dir / "discovery"
        discovery_base.mkdir(parents=True, exist_ok=True)

        # Handle duplicate slugs
        slug = base_slug
        counter = 2
        while (discovery_base / slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        idea_dir = discovery_base / slug
        idea_dir.mkdir(parents=True, exist_ok=True)

        # Write seed.md
        seed_content = f"---\nslug: {slug}\ncreated: {datetime.date.today().isoformat()}\n---\n\n# Seed idea\n\n{idea}\n"
        (idea_dir / "seed.md").write_text(seed_content, encoding="utf-8")

        # Spawn discovery-moderator
        task_prompt = (
            f"Working directory: `docs/shipflow/discovery/{slug}/`.\n"
            "Run the full 2-round dialogue with the three personas (tech, ux, business).\n"
            "Converge to `questions.md` and a stitched `dialogue.md`.\n"
            "Report back with the number of questions produced."
        )

        agent_path = self._get_agent_path("discovery-moderator")
        logger.info("Spawning discovery-moderator...")
        self.runner.spawn_subagent(agent_file_path=agent_path, task_prompt=task_prompt)

        questions_file = idea_dir / "questions.md"
        if questions_file.exists():
            return questions_file.read_text(encoding="utf-8")
        else:
            return "Error: questions.md was not generated by the moderator."

    def sf_brief(self, slug: str):
        """
        Assemble the brief after user has answered questions.
        """
        logger.info(f"Running /sf-brief for slug: {slug}")
        idea_dir = self.docs_dir / "discovery" / slug
        if not idea_dir.exists():
            raise ValueError(f"Discovery directory for slug '{slug}' not found.")

        # Spawn tech, ux, business personas in Synthesis mode
        personas = ["discovery-tech-persona", "discovery-ux-persona", "discovery-business-persona"]
        for persona in personas:
            agent_path = self._get_agent_path(persona)
            task_prompt = (
                f"Working directory: `docs/shipflow/discovery/{slug}/`.\n"
                f"Run in Synthesis mode. Read `seed.md`, `questions.md`, and `answers.md`.\n"
                f"Write your slice of the brief."
            )
            logger.info(f"Spawning {persona} in Synthesis mode...")
            self.runner.spawn_subagent(agent_file_path=agent_path, task_prompt=task_prompt)

        # Assemble the brief (normally done by skill script)
        briefs_dir = self.docs_dir / "briefs"
        briefs_dir.mkdir(parents=True, exist_ok=True)

        brief_num = len(list(briefs_dir.glob("BRIEF-*.md"))) + 1
        brief_filename = f"BRIEF-{brief_num:03d}-{slug}.md"
        brief_path = briefs_dir / brief_filename

        assembled_content = f"# Product Brief: {slug}\n\n"

        for slice_name in ["slice-business.md", "slice-ux.md", "slice-tech.md"]:
            slice_file = idea_dir / slice_name
            if slice_file.exists():
                assembled_content += slice_file.read_text(encoding="utf-8") + "\n\n"

        brief_path.write_text(assembled_content, encoding="utf-8")
        logger.info(f"Assembled brief at {brief_path}")

        # Spawn challenger
        challenger_path = self._get_agent_path("challenger")
        challenger_prompt = (
            f"Working directory: `docs/shipflow/discovery/{slug}/` and `{brief_path}`.\n"
            "Read the seed, answers, and the assembled brief. Resolve challenges internally from the materials.\n"
            "Escalate remaining gaps to `open-questions.md`."
        )
        logger.info("Spawning challenger...")
        self.runner.spawn_subagent(agent_file_path=challenger_path, task_prompt=challenger_prompt)

        return str(brief_path)

    def sf_check_brief(self, brief_file: str):
        """
        Gate 1: advisory review by tech-lead + product-lead.
        """
        logger.info(f"Running /sf-check-brief for {brief_file}")

        for lead in ["tech-lead", "product-lead"]:
            agent_path = self._get_agent_path(lead)
            task_prompt = (
                f"Review the brief at `{brief_file}`.\n"
                f"Write a reviewer breadcrumb with a `Verdict:` line (approve | needs-changes | reject)."
            )
            logger.info(f"Spawning {lead} for review...")
            self.runner.spawn_subagent(agent_file_path=agent_path, task_prompt=task_prompt)

    def sf_spec(self, brief_file: str):
        """
        Translate an approved brief into 5–10 stories.
        """
        logger.info(f"Running /sf-spec for {brief_file}")

        agent_path = self._get_agent_path("spec-author")
        task_prompt = (
            f"Read `{brief_file}`.\n"
            "Slice the brief into stories under `docs/shipflow/stories/`.\n"
            "Each story should have `brief: <brief_id>` in frontmatter, acceptance criteria, dependencies, and size.\n"
            "Flag 1–2 stories that need an ADR before they can be built."
        )
        logger.info("Spawning spec-author...")
        self.runner.spawn_subagent(agent_file_path=agent_path, task_prompt=task_prompt)

        # In a real run, spec-author writes the files, then we spawn challenger.
        # Spawning challenger for spec
        challenger_path = self._get_agent_path("challenger")
        challenger_prompt = (
            f"Read the approved brief `{brief_file}` and the newly-written stories under `docs/shipflow/stories/`.\n"
            "Escalate gaps to a Spec-level `open-questions.md` under the stories dir."
        )
        logger.info("Spawning challenger for spec...")
        self.runner.spawn_subagent(agent_file_path=challenger_path, task_prompt=challenger_prompt)

    def sf_check_plan(self, story_dir: str = "docs/shipflow/stories"):
        """
        Gate 2: advisory review. Spawns tech-lead.
        """
        logger.info(f"Running /sf-check-plan for stories in {story_dir}")
        agent_path = self._get_agent_path("tech-lead")
        task_prompt = (
            f"Review the stories under `{story_dir}`.\n"
            "Write an advisory review. Append a Verdict per-story."
        )
        logger.info("Spawning tech-lead for per-story review...")
        self.runner.spawn_subagent(agent_file_path=agent_path, task_prompt=task_prompt)
